### ISSUE TITLE
Wrong implementation of AvgPool in E_MHSA

### ISSUE THREAD

**Issue by bonlime** [bytedance/Next-ViT#2]
Hi! 
First of all very interesting paper with good ideas. I've looked into your code and your implementation of AvgPool seems to be wrong. Usually when we speak about AvgPool for images we assume a box filter with kernel_size=(size, size) and stride=size. 

In your implementation you
1. take input of size: (B, C, H, W)
2. reshape it to (B, H*W, C)
3. in E_MHSA reshape it to (B, Heads, H * W, C / Heads)
4. in case of **sr_ratio != 1** you reshape to (B, Heads, H * W, C / Heads)
5. Apply AvgPool 1d to the tensor above with `kernel_size=size * size, stride=size * size`. This is NOT IDENTICAL to AvgPool2d.

The problem is that in this implementation your performing avg-pooling of rows, and it leads to leakage of information from one border to another and also doesn't use any information in vertical dimension. Below is an example of tensor and it's mean inside your E_MHSA.

```
BS, DIM, SZ = 1, 1, 4
inp = torch.arange(SZ * SZ).float().view(BS, SZ * SZ, DIM)
E_MHSA(dim=DIM, sr_ratio=2, head_dim=1)(inp)

inp = tensor([
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

mean_inp (after self.sr(_x)): tensor([ 1.5000,  5.5000,  9.5000, 13.5000])
```

It's obvious it calculate average only inside rows. I would assume you used such implementation to avoid reshaping back to (B, C, H, W) for performing AvgPool2d, but this leads to a totally different pooling. 

As a side note I would say that all this `(B, C, H, W) -> (B, N, C) -> (B, C, H, W)` permutations are not really needed and you could boost speed of your network by re-implementing E_MHSA to work on `(B, C, H, W)` tensors as inputs.

**Comment by pawopawo** [comment]
Thank you for your attention

We treat the input of pooling as tokens, which is 1d. It is not necessary to resize tokens into images to perform pooling.

If using avg-pool 2d, we need to reshape the token to a 2d image`(B, N, C) -> (B, C, H, W)`, and then `(B, C, H, W) -> (B, N, C)`. This also increases the overhead of network.

We think this has little effect on the experiment. If you are interested, you can do an experiment to compare~

**Comment by XiaXin-Aloys** [comment]
Thank you for your attention

We treat the input of pooling as tokens, which is 1d. It is not necessary to resize tokens into images to perform pooling.

If using avg-pool2d, we need to reshape the token to a 2d image`(B, N, C) -> (B, C, H, W)`, and then `(B, C, H, W) -> (B, N, C)`. This also increases the overhead of network.

We think this has little effect on the result. If you are interested, you can do an experiment to compare~
