### ISSUE TITLE
add models to Hugging Face Hub

### ISSUE THREAD

**Issue by AK391** [bytedance/Next-ViT#3]
Hi!

Would you be interested in sharing your models in the [Hugging Face Hub](http://hf.co/models)? The Hub offers free hosting and it would make your work more accessible and visible to the rest of the ML community.  We can help you set up a bytedance organization.

Some of the benefits of sharing your models through the Hub would be:
* versioning, commit history and diffs
* repos provide useful metadata about their tasks, languages, metrics, etc that make them discoverable
* multiple features from TensorBoard visualizations, PapersWithCode integration, and more
* wider reach of your work to the ecosystem

Creating the repos and adding new models should be a relatively straightforward process if you've used Git before. This is a [step-by-step guide](https://huggingface.co/docs/hub/adding-a-model) explaining the process in case you're interested. Please let us know if you would be interested and if you have any questions.

and you can also setup a gradio demo for your model by following this guide: https://gradio.app/getting_started/

here is a example of a gradio demo: https://huggingface.co/spaces/adirik/OWL-ViT
and the code: https://huggingface.co/spaces/adirik/OWL-ViT/blob/main/app.py

Happy to hear your thoughts,
**Ahsen and the Hugging Face team**

**Comment by Jiashi-Li** [comment]
Thanks for your invatation, we will consider it.
