### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by JiangWeiHn** [bytedance/Next-ViT#4]
请问分割模型适合在边缘端部署么？我们的硬件采用nvidia orin，我下载的pretrained model都700多MB了，能部署么？

**Comment by Jiashi-Li** [comment]
700多MB的pretrained model中 包括了一些optimizer的参数，这些参数在部署的时候是不会用到的，推理时模型的大小也就100多M，部署于nvidia orin应该没什么问题~

**Comment by JiangWeiHn** [comment]
好的 谢谢

**Comment by shuyuan-wang** [comment]
@JiangWeiHn 大佬，请问你们orin上部署完latency和MAP咋样
