### ISSUE TITLE
how to deploy  the Next_ViT  detection?

### ISSUE THREAD

**Issue by Chen-cyw** [bytedance/Next-ViT#6]
how to deploy  the Next_ViT  detection?  use  mmdetection  tools?

**Comment by Jiashi-Li** [comment]
Yes，if you need to deploy Next_ViT detection to TensorRT,  You can refer to this [script](https://github.com/bytedance/Next-ViT/blob/main/deployment/export_tensorrt_engine.py) and the related scripts in mmdetetion.
