### ISSUE TITLE
Error in conversion to ONNX

### ISSUE THREAD

**Issue by TrNgTinh** [bytedance/Next-ViT#7]
I used the NextVit as backbone for training a face embedding model and the accuracy was pretty good. But I tried to convert it to onnx and deploy on edge device, however, there was an error like this:
```
einops.py:314: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  known = {axis for axis in composite_axis if axis_name2known_length[axis] != _unknown_axis_length}
```
This error prevents me from inference the model and I don't know how to fix this, can anyone help me with this, thanks :D

**Comment by Jiashi-Li** [comment]
In my opinion, this is just a conversion warning, not an error.  The onnx model will be exported to the target onnx path as expected(please check this). Can you describe how this warning prevents you from inference the model in detail?

**Comment by TrNgTinh** [comment]
Thank you for your early response @Jiashi-Li . I can still use it for inference. But I just want to make sure it may be affect accuracy..I'll check again and let you know results soon. Tks very much.
