### ISSUE TITLE
关于论文对E-MHSA的空间缩减率的描述疑问

### ISSUE THREAD

**Issue by WYHZQ** [bytedance/Next-ViT#8]
作者您好！

最近我正在研读您的论文。您在论文的3.5节中提到E-MHSA在不同stage的空间缩减率为8,4,2,1.   但是按照我对论文的理解，stage1中是没有E-MHSA模块的（仅有NCB没有NTB）。那您所描述的缩减率为8是什么意思呢？还是我对您的论文哪里理解有误呢？还望您能解惑！
万分感谢。

![图片](https://user-images.githubusercontent.com/75660358/194759114-9fe16d95-9994-4200-800b-6b241d45faa1.png)

**Comment by Jiashi-Li** [comment]
感谢你的关注，你的理解是正确的，这里的[8, 4, 2, 1]里的8的确是没用到的。

**Comment by WYHZQ** [comment]
谢谢您的回复，解决了我的疑问，感谢!
