### ISSUE TITLE
论文fig5的问题

### ISSUE THREAD

**Issue by guoguo1314** [bytedance/Next-ViT#9]
您好，请问你fig5的傅里叶图和热力图怎么生成的？有没有代码或者链接分享一下，谢谢博主了！

**Comment by jiaming-lee** [comment]
mark

**Comment by Jiashi-Li** [comment]
热力图我们参考的是这个代码https://github.com/yitu-opensource/T2T-ViT/blob/main/visualization_vit.ipynb
傅里叶图我们参考的是这个https://blog.csdn.net/qq_42451251/article/details/107832069

**Comment by guoguo1314** [comment]
> 热力图我们参考的是这个代码https://github.com/yitu-opensource/T2T-ViT/blob/main/visualization_vit.ipynb 傅里叶图我们参考的是这个https://blog.csdn.net/qq_42451251/article/details/107832069

谢谢博主！

**Comment by guoguo1314** [comment]
博主，我又来了！就是你那个傅里叶图，是用的np.fft.fft2吗？ff2(图)，这个图是热力图，还是最后一层输出的特征图？谢谢了！
